using System.ComponentModel.DataAnnotations;
namespace AtiqSalon.Api.Domain;

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTimeOffset CreatedAtUtc { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAtUtc { get; set; } = DateTimeOffset.UtcNow; [Timestamp] public uint Version { get; set; } }
public abstract class TenantEntity : Entity { public Guid TenantId { get; set; } }
public sealed class Tenant : Entity { public string Name { get; set; } = ""; public string Slug { get; set; } = ""; public string Status { get; set; } = "active"; }
public sealed class Organization : TenantEntity { public string LegalName { get; set; } = ""; public string TradingName { get; set; } = ""; public string Slug { get; set; } = ""; public string Email { get; set; } = ""; public string? Phone { get; set; } public string CountryCode { get; set; } = "AE"; public string DefaultCurrency { get; set; } = "AED"; public string DefaultLanguage { get; set; } = "en"; public string TimeZone { get; set; } = "Asia/Dubai"; public string Status { get; set; } = "active"; }
public sealed class Branch : TenantEntity { public Guid OrganizationId { get; set; } public string Name { get; set; } = ""; public string Code { get; set; } = ""; public string? Email { get; set; } public string? Phone { get; set; } public string? AddressLine1 { get; set; } public string? AddressLine2 { get; set; } public string? City { get; set; } public string? Region { get; set; } public string CountryCode { get; set; } = "AE"; public string TimeZone { get; set; } = "Asia/Dubai"; public bool IsActive { get; set; } = true; }
public sealed class User : TenantEntity { public string Email { get; set; } = ""; public string NormalizedEmail { get; set; } = ""; public string DisplayName { get; set; } = ""; public string PasswordHash { get; set; } = ""; public string Status { get; set; } = "active"; public bool EmailVerified { get; set; } public string? EmailVerificationToken { get; set; } public int FailedLoginCount { get; set; } public DateTimeOffset? LastLoginAtUtc { get; set; } public string[] Roles { get; set; } = []; }
public sealed class UserBranchAssignment : TenantEntity { public Guid UserId { get; set; } public Guid OrganizationId { get; set; } public Guid BranchId { get; set; } public bool IsActive { get; set; } = true; }
public sealed class RefreshSession : TenantEntity { public Guid UserId { get; set; } public string TokenHash { get; set; } = ""; public DateTimeOffset ExpiresAtUtc { get; set; } public DateTimeOffset? RevokedAtUtc { get; set; } public string? ReplacedByTokenHash { get; set; } }
public sealed class AuditEvent : TenantEntity { public Guid? OrganizationId { get; set; } public Guid? ActorUserId { get; set; } public string Action { get; set; } = ""; public string EntityType { get; set; } = ""; public string? EntityId { get; set; } public string Source { get; set; } = "api"; public string? IpAddress { get; set; } public string? UserAgent { get; set; } public string? BeforeJson { get; set; } public string? AfterJson { get; set; } public DateTimeOffset OccurredAtUtc { get; set; } public string CorrelationId { get; set; } = Guid.NewGuid().ToString("N"); public static AuditEvent Security(User user, string action, HttpContext http) => new() { TenantId = user.TenantId, ActorUserId = user.Id, Action = action, EntityType = "User", EntityId = user.Id.ToString(), Source = "api", IpAddress = http.Connection.RemoteIpAddress?.ToString(), UserAgent = http.Request.Headers.UserAgent.ToString(), OccurredAtUtc = DateTimeOffset.UtcNow, CorrelationId = http.TraceIdentifier }; }
public static class Slug { public static string Create(string value) => string.Join("-", value.Trim().ToLowerInvariant().Split(' ', StringSplitOptions.RemoveEmptyEntries)).Substring(0, Math.Min(80, string.Join("-", value.Trim().ToLowerInvariant().Split(' ', StringSplitOptions.RemoveEmptyEntries)).Length)); }
