namespace AtiqSalon.Api.Domain;

public sealed class ServiceCategory : TenantEntity { public Guid OrganizationId { get; set; } public string Name { get; set; } = ""; public string LocalizedNameJson { get; set; } = "{}"; public string? Description { get; set; } public int DisplayOrder { get; set; } public bool IsActive { get; set; } = true; }
public sealed class SalonService : TenantEntity { public Guid OrganizationId { get; set; } public Guid CategoryId { get; set; } public string Name { get; set; } = ""; public string LocalizedNameJson { get; set; } = "{}"; public string? Description { get; set; } public string LocalizedDescriptionJson { get; set; } = "{}"; public string Code { get; set; } = ""; public int DurationMinutes { get; set; } public int CleanupMinutes { get; set; } public int ProcessingMinutes { get; set; } public decimal BasePrice { get; set; } public string CurrencyCode { get; set; } = "AED"; public string? TaxCategoryCode { get; set; } public string DepositType { get; set; } = "None"; public decimal DepositValue { get; set; } public string ColorCode { get; set; } = "#657a68"; public bool OnlineBookingEnabled { get; set; } public bool RequiresConsultation { get; set; } public bool RequiresCustomerNotes { get; set; } public bool RequiresResource { get; set; } public int MaxConcurrentBookings { get; set; } = 1; public int DisplayOrder { get; set; } public bool IsActive { get; set; } = true; }
public sealed class BranchService : TenantEntity { public Guid OrganizationId { get; set; } public Guid BranchId { get; set; } public Guid ServiceId { get; set; } public decimal? PriceOverride { get; set; } public int? DurationOverrideMinutes { get; set; } public bool? OnlineBookingEnabledOverride { get; set; } public bool IsActive { get; set; } = true; }
public sealed class ServiceAddOn : TenantEntity { public Guid OrganizationId { get; set; } public Guid ParentServiceId { get; set; } public string Name { get; set; } = ""; public string? Description { get; set; } public int AdditionalDurationMinutes { get; set; } public decimal AdditionalPrice { get; set; } public bool IsActive { get; set; } = true; public int DisplayOrder { get; set; } }
public sealed class StaffMember : TenantEntity { public Guid OrganizationId { get; set; } public Guid? LinkedUserId { get; set; } public string EmployeeCode { get; set; } = ""; public string FirstName { get; set; } = ""; public string LastName { get; set; } = ""; public string DisplayName { get; set; } = ""; public string? Email { get; set; } public string? Phone { get; set; } public string? JobTitle { get; set; } public string? Biography { get; set; } public string? ProfileImageObjectKey { get; set; } public string PreferredLanguage { get; set; } = "en"; public string EmploymentStatus { get; set; } = "Active"; public DateOnly? HireDate { get; set; } public DateOnly? EndDate { get; set; } public Guid? DefaultBranchId { get; set; } public bool OnlineBookingEnabled { get; set; } public bool AcceptsWalkIns { get; set; } public string ColorCode { get; set; } = "#657a68"; public bool IsActive { get; set; } = true; }
public sealed class StaffBranchAssignment : TenantEntity { public Guid OrganizationId { get; set; } public Guid StaffMemberId { get; set; } public Guid BranchId { get; set; } public DateOnly StartDate { get; set; } public DateOnly? EndDate { get; set; } public bool IsPrimary { get; set; } public bool IsActive { get; set; } = true; }
public sealed class StaffServiceCapability : TenantEntity { public Guid OrganizationId { get; set; } public Guid StaffMemberId { get; set; } public Guid ServiceId { get; set; } public Guid? BranchId { get; set; } public bool CanPerform { get; set; } = true; public decimal? PriceOverride { get; set; } public int? DurationOverrideMinutes { get; set; } public bool OnlineBookingEnabled { get; set; } public string SkillLevel { get; set; } = "Standard"; }
public sealed class Customer : TenantEntity { public Guid OrganizationId { get; set; } public string CustomerNumber { get; set; } = ""; public string FirstName { get; set; } = ""; public string LastName { get; set; } = ""; public string DisplayName { get; set; } = ""; public string? Email { get; set; } public string? NormalizedEmail { get; set; } public string? PhoneCountryCode { get; set; } public string? PhoneNumber { get; set; } public string? NormalizedPhone { get; set; } public string PreferredLanguage { get; set; } = "en"; public DateOnly? DateOfBirth { get; set; } public string Gender { get; set; } = "NotSpecified"; public Guid? PreferredBranchId { get; set; } public Guid? PreferredStaffMemberId { get; set; } public string Source { get; set; } = "Reception"; public bool MarketingEmailConsent { get; set; } public bool MarketingSmsConsent { get; set; } public bool MarketingWhatsAppConsent { get; set; } public DateTimeOffset? ConsentUpdatedAtUtc { get; set; } public string? Notes { get; set; } public bool IsBlocked { get; set; } public string? BlockReason { get; set; } public DateTimeOffset? LastVisitAtUtc { get; set; } }
public sealed class CustomerTag : TenantEntity { public Guid OrganizationId { get; set; } public string Name { get; set; } = ""; public string ColorCode { get; set; } = "#657a68"; public bool IsActive { get; set; } = true; }
public sealed class CustomerTagAssignment : TenantEntity { public Guid OrganizationId { get; set; } public Guid CustomerId { get; set; } public Guid CustomerTagId { get; set; } }
public sealed class CustomerNote : TenantEntity { public Guid OrganizationId { get; set; } public Guid CustomerId { get; set; } public Guid AuthorUserId { get; set; } public string NoteType { get; set; } = "General"; public string Content { get; set; } = ""; public bool IsSensitive { get; set; } }
public sealed class SalonResource : TenantEntity { public Guid OrganizationId { get; set; } public Guid BranchId { get; set; } public string Name { get; set; } = ""; public string Code { get; set; } = ""; public string Type { get; set; } = "Other"; public string? Description { get; set; } public int Capacity { get; set; } = 1; public string ColorCode { get; set; } = "#657a68"; public bool OnlineBookingVisible { get; set; } public bool IsActive { get; set; } = true; }
public sealed class ServiceResourceRequirement : TenantEntity { public Guid OrganizationId { get; set; } public Guid ServiceId { get; set; } public string ResourceType { get; set; } = "Other"; public Guid? SpecificResourceId { get; set; } public int QuantityRequired { get; set; } = 1; public bool IsMandatory { get; set; } = true; }
public sealed class BranchBusinessHours : TenantEntity { public Guid OrganizationId { get; set; } public Guid BranchId { get; set; } public DayOfWeek DayOfWeek { get; set; } public TimeOnly OpenTime { get; set; } public TimeOnly CloseTime { get; set; } public bool IsClosed { get; set; } public DateOnly EffectiveFrom { get; set; } public DateOnly? EffectiveTo { get; set; } }
public sealed class BranchClosure : TenantEntity { public Guid OrganizationId { get; set; } public Guid BranchId { get; set; } public string Name { get; set; } = ""; public DateTimeOffset StartsAtUtc { get; set; } public DateTimeOffset EndsAtUtc { get; set; } public string? Reason { get; set; } public bool IsFullDay { get; set; } }
public sealed class StaffWorkingHours : TenantEntity { public Guid OrganizationId { get; set; } public Guid StaffMemberId { get; set; } public Guid BranchId { get; set; } public DayOfWeek DayOfWeek { get; set; } public TimeOnly StartTime { get; set; } public TimeOnly EndTime { get; set; } public DateOnly EffectiveFrom { get; set; } public DateOnly? EffectiveTo { get; set; } }
public sealed class StaffAvailabilityOverride : TenantEntity { public Guid OrganizationId { get; set; } public Guid StaffMemberId { get; set; } public Guid BranchId { get; set; } public DateTimeOffset StartsAtUtc { get; set; } public DateTimeOffset EndsAtUtc { get; set; } public string OverrideType { get; set; } = "Unavailable"; public string? Reason { get; set; } }
public sealed class StaffBreakRule : TenantEntity { public Guid OrganizationId { get; set; } public Guid StaffMemberId { get; set; } public Guid BranchId { get; set; } public DayOfWeek DayOfWeek { get; set; } public TimeOnly StartTime { get; set; } public TimeOnly EndTime { get; set; } public DateOnly EffectiveFrom { get; set; } public DateOnly? EffectiveTo { get; set; } }
public sealed class OrganizationBookingSettings : TenantEntity { public Guid OrganizationId { get; set; } public int DefaultSlotIntervalMinutes { get; set; } = 15; public int MinimumAdvanceBookingMinutes { get; set; } = 60; public int MaximumAdvanceBookingDays { get; set; } = 90; public int CancellationWindowMinutes { get; set; } = 1440; public int RescheduleWindowMinutes { get; set; } = 1440; public bool AllowSameDayBooking { get; set; } = true; public bool AllowGuestBooking { get; set; } = true; public bool RequireEmail { get; set; } public bool RequirePhone { get; set; } = true; public string DefaultTimeZone { get; set; } = "Asia/Dubai"; public string DefaultBookingStatus { get; set; } = "Confirmed"; public bool AutoConfirmOnlineBookings { get; set; } public bool AllowCustomerCancellation { get; set; } = true; public bool AllowCustomerRescheduling { get; set; } = true; public bool AllowWaitlist { get; set; } }
public sealed class BranchBookingSettings : TenantEntity { public Guid OrganizationId { get; set; } public Guid BranchId { get; set; } public int? SlotIntervalMinutes { get; set; } public int? MinimumAdvanceBookingMinutes { get; set; } public int? CancellationWindowMinutes { get; set; } public bool? AutoConfirmOnlineBookings { get; set; } public bool? AllowGuestBooking { get; set; } public bool? AllowWaitlist { get; set; } public bool OnlineBookingEnabled { get; set; } = true; }
public sealed class ServiceBookingRule : TenantEntity { public Guid OrganizationId { get; set; } public Guid ServiceId { get; set; } public int? MinimumLeadTimeMinutes { get; set; } public int? MaximumAdvanceDays { get; set; } public int? CancellationWindowMinutes { get; set; } public string? DepositType { get; set; } public decimal? DepositValue { get; set; } public bool? OnlineBookingEnabled { get; set; } public bool? AllowNewCustomers { get; set; } public bool? AllowSpecificStaffSelection { get; set; } }
public sealed class Appointment : TenantEntity { public Guid OrganizationId { get; set; } public Guid BranchId { get; set; } public string AppointmentNumber { get; set; } = ""; public Guid CustomerId { get; set; } public string Status { get; set; } = "Draft"; public string Source { get; set; } = "Reception"; public DateTimeOffset StartAtUtc { get; set; } public DateTimeOffset EndAtUtc { get; set; } public string BranchTimeZone { get; set; } = "Asia/Dubai"; public string CustomerDisplayName { get; set; } = ""; public string? CustomerPhone { get; set; } public string? CustomerEmail { get; set; } public string? CustomerNotes { get; set; } public string? InternalNotes { get; set; } public string? CancellationReason { get; set; } public DateTimeOffset? CancelledAtUtc { get; set; } public Guid? CancelledByUserId { get; set; } public Guid? CreatedByUserId { get; set; } public Guid? UpdatedByUserId { get; set; } public DateTimeOffset? ConfirmedAtUtc { get; set; } public DateTimeOffset? CheckedInAtUtc { get; set; } public DateTimeOffset? StartedAtUtc { get; set; } public DateTimeOffset? CompletedAtUtc { get; set; } public DateTimeOffset? NoShowMarkedAtUtc { get; set; } public string? IdempotencyKey { get; set; } }
public sealed class AppointmentService : TenantEntity { public Guid OrganizationId { get; set; } public Guid AppointmentId { get; set; } public Guid ServiceId { get; set; } public Guid StaffMemberId { get; set; } public DateTimeOffset StartAtUtc { get; set; } public DateTimeOffset EndAtUtc { get; set; } public int DurationMinutes { get; set; } public int CleanupMinutes { get; set; } public decimal UnitPrice { get; set; } public decimal DiscountAmount { get; set; } public decimal TaxAmount { get; set; } public decimal TotalAmount { get; set; } public string DepositType { get; set; } = "None"; public decimal DepositValue { get; set; } public int Sequence { get; set; } public string Status { get; set; } = "Scheduled"; public string? CustomerNotes { get; set; } public string? InternalNotes { get; set; } }
public sealed class AppointmentResourceReservation : TenantEntity { public Guid OrganizationId { get; set; } public Guid AppointmentId { get; set; } public Guid AppointmentServiceId { get; set; } public Guid ResourceId { get; set; } public DateTimeOffset StartsAtUtc { get; set; } public DateTimeOffset EndsAtUtc { get; set; } public int Quantity { get; set; } = 1; }
public sealed class AppointmentStatusHistory : TenantEntity { public Guid OrganizationId { get; set; } public Guid AppointmentId { get; set; } public string PreviousStatus { get; set; } = ""; public string NewStatus { get; set; } = ""; public Guid? ChangedByUserId { get; set; } public string? Reason { get; set; } public DateTimeOffset ChangedAtUtc { get; set; } = DateTimeOffset.UtcNow; }
public sealed class NotificationMessage : TenantEntity { public Guid OrganizationId { get; set; } public Guid? BranchId { get; set; } public Guid? CustomerId { get; set; } public Guid? AppointmentId { get; set; } public string Channel { get; set; } = "Email"; public string TemplateCode { get; set; } = ""; public string Recipient { get; set; } = ""; public string? Subject { get; set; } public string Body { get; set; } = ""; public string Status { get; set; } = "Pending"; public DateTimeOffset? ScheduledForUtc { get; set; } public DateTimeOffset? SentAtUtc { get; set; } public DateTimeOffset? FailedAtUtc { get; set; } public string? FailureReason { get; set; } public string? ProviderMessageId { get; set; } public string? IdempotencyKey { get; set; } }
public sealed class AppointmentReminderRule : TenantEntity { public Guid OrganizationId { get; set; } public Guid? BranchId { get; set; } public string Channel { get; set; } = "Email"; public int MinutesBeforeAppointment { get; set; } public string TemplateCode { get; set; } = ""; public bool IsActive { get; set; } = true; }

public static class AppointmentLifecycle
{
    private static readonly IReadOnlyDictionary<string, string[]> Allowed = new Dictionary<string, string[]> { ["Draft"] = ["PendingConfirmation", "Confirmed", "Cancelled"], ["PendingConfirmation"] = ["Confirmed", "Cancelled"], ["Confirmed"] = ["CheckedIn", "Cancelled", "NoShow"], ["CheckedIn"] = ["InProgress", "Cancelled"], ["InProgress"] = ["Completed"], ["Completed"] = [], ["Cancelled"] = [], ["NoShow"] = [] };
    public static bool CanTransition(string current, string next) => Allowed.TryGetValue(current, out var transitions) && transitions.Contains(next);
}
public static class ServiceRules
{
    public static IReadOnlyDictionary<string, string[]> Validate(SalonService service)
    {
        var errors = new Dictionary<string, string[]>();
        if (service.DurationMinutes <= 0) errors["durationMinutes"] = ["Duration must be greater than zero."];
        if (service.CleanupMinutes < 0 || service.ProcessingMinutes < 0) errors["timing"] = ["Cleanup and processing time cannot be negative."];
        if (service.BasePrice < 0) errors["basePrice"] = ["Price cannot be negative."];
        if (service.DepositType == "Percentage" && service.DepositValue is < 0 or > 100) errors["depositValue"] = ["Percentage deposit must be between 0 and 100."];
        if (service.DepositType == "FixedAmount" && service.DepositValue > service.BasePrice) errors["depositValue"] = ["Fixed deposit cannot exceed service price."];
        return errors;
    }
}
